// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  app.service('ExceptionMapperService', [
    '$http', function($http) {
      this.parseError = function(errorList) {
        var e, errorMsgs, i, j, k, len, len1, self, v;
        errorMsgs = [];
        self = this;
        if (errorList instanceof Array) {
          for (i = 0, len = errorList.length; i < len; i++) {
            e = errorList[i];
            errorMsgs.push(e);
          }
        } else if (errorList.constructor === Object) {
          for (k in errorList) {
            v = errorList[k];
            if (v instanceof Array) {
              for (j = 0, len1 = v.length; j < len1; j++) {
                e = v[j];
                errorMsgs.push(e);
              }
            } else {
              errorMsgs.push(v);
            }
          }
        } else {
          errorMsgs.push(errorList);
        }
        return errorMsgs;
      };
    }
  ]);

}).call(this);
