// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  app.service('UserService', [
    '$http', '$q', '$rootScope', 'API_URL', function($http, $q, $rootScope, API_URL) {
      this.create = function(title) {
        return $http.post(API_URL + 'task', {
          "title": title
        });
      };
      this.login = function(credentials) {
        return $http.post(API_URL + 'auth', credentials);
      };
      this.tasks = function() {
        return $http.get(API_URL + 'task');
      };
      this.get_running_task = function() {
        return $http.get(API_URL + 'task/current');
      };
      this.pause_task = function($task_id) {
        return $http.put(API_URL + 'task/' + $task_id, {
          "state": "pause"
        });
      };
      this.stop_task = function($task_id, title) {
        return $http.put(API_URL + 'task/' + $task_id, {
          "state": "stop",
          "title": title
        });
      };
      this.continue_task = function($task_id) {
        return $http.put(API_URL + 'task/' + $task_id, {
          "state": "continue"
        });
      };
    }
  ]);

}).call(this);
