// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  app.factory('authInterceptor', function($rootScope, $q, $window, $location) {
    return {
      request: function(config) {
        if ($window.sessionStorage.auth_token) {
          config.headers.Authorization = 'Basic ' + $window.sessionStorage.auth_token;
        }
        return config;
      },
      response: function(response) {
        if (response.status === 401) {
          delete $window.sessionStorage.username;
          delete $window.sessionStorage.password;
          $location.path('/login');
        } else {

        }
        return response || $q.when(response);
      }
    };
  });

  app.config(function($httpProvider, $locationProvider, $logProvider) {
    $httpProvider.interceptors.push('authInterceptor');
  });

}).call(this);
