// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  app.config([
    '$stateProvider', '$httpProvider', '$urlRouterProvider', '$controllerProvider', '$compileProvider', '$filterProvider', '$provide', '$ocLazyLoadProvider', 'JS_REQUIRES', function($stateProvider, $httpProvider, $urlRouterProvider, $controllerProvider, $compileProvider, $filterProvider, $provide, $ocLazyLoadProvider, jsRequires) {
      app.controller = $controllerProvider.register;
      app.directive = $compileProvider.directive;
      app.filter = $filterProvider.register;
      app.factory = $provide.factory;
      app.service = $provide.service;
      app.constant = $provide.constant;
      app.value = $provide.value;
      app.constant('API_URL', 'http://localhost:8000/api/v1/');
      $ocLazyLoadProvider.config({
        debug: true,
        events: true,
        modules: jsRequires.modules
      });
      $urlRouterProvider.otherwise("/");
      return $stateProvider.state('root', {
        abstract: true,
        views: {
          'header': {
            templateUrl: "partials/header.html",
            controller: 'headerCtrl'
          }
        }
      }).state('homepage', {
        parent: 'root',
        url: "/",
        views: {
          'content': {
            templateUrl: "partials/homepage.html",
            controller: 'homeCtrl',
            resolve: {
              tasks: [
                '$window', '$location', 'UserService', function($window, $location, UserService) {
                  if (!$window.sessionStorage.auth_token) {
                    $location.path('/login');
                  }
                  return UserService.tasks();
                }
              ],
              running_task: [
                'UserService', function(UserService) {
                  return UserService.get_running_task();
                }
              ]
            }
          }
        }
      }).state('login', {
        parent: 'root',
        url: "/login",
        views: {
          'content': {
            templateUrl: "partials/login.html",
            controller: 'loginCtrl'
          }
        }
      }).state('logout', {
        parent: 'root',
        url: "/logout",
        views: {
          'content': {
            templateUrl: "partials/login.html",
            controller: 'logoutCtrl'
          }
        }
      });
    }
  ]);

}).call(this);
