// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  app.controller('loginCtrl', [
    '$window', '$location', '$scope', 'UserService', 'StorageService', 'ExceptionMapperService', function($window, $location, $scope, UserService, StorageService, ExceptionMapperService) {
      var ClearForm;
      $scope.alerts = [];
      $scope.addAlert = function(alert_type, msg) {
        if (alert_type == null) {
          alert_type = 'error';
        }
        if (msg == null) {
          msg = 'Wystąpił błąd';
        }
        if (alert_type === 'success') {
          $scope.alerts.push({
            alert_type: 'success',
            msg: msg
          });
        }
        if (alert_type === 'error') {
          return $scope.alerts.push({
            type: 'danger',
            msg: msg
          });
        }
      };
      $scope.closeAlert = function(index) {
        return $scope.alerts.splice(index, 1);
      };
      ClearForm = function() {
        $scope.userEmail = '';
        return $scope.userPassword = '';
      };
      return $scope.logIn = function() {
        var data, response;
        data = {
          username: $scope.userName,
          password: $scope.userPassword
        };
        response = UserService.login(data);
        return response.success(function(data, status, headers) {
          var basic_auth_token;
          delete $window.sessionStorage.auth_token;
          delete $window.sessionStorage.username;
          basic_auth_token = StorageService.encrypt_base64($scope.userName + ":" + $scope.userPassword);
          $window.sessionStorage.username = $scope.userName;
          $window.sessionStorage.auth_token = basic_auth_token;
          return $window.location.href = '/';
        }).error(function(data, status, headers) {
          var error, errorMsgs, i, len;
          delete $window.sessionStorage.username;
          delete $window.sessionStorage.auth_token;
          $scope.alerts = [];
          errorMsgs = ExceptionMapperService.parseError(data['msg']);
          for (i = 0, len = errorMsgs.length; i < len; i++) {
            error = errorMsgs[i];
            $scope.addAlert('error', error);
          }
          return ClearForm();
        });
      };
    }
  ]);

  app.controller('logoutCtrl', [
    '$window', '$location', '$scope', function($window, $location, $scope) {
      delete $window.sessionStorage.username;
      delete $window.sessionStorage.auth_token;
      return $window.location.href = '/';
    }
  ]);

}).call(this);
