// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  app.controller('footerCtrl', [
    '$scope', '$document', 'team', 'pages', function($scope, $document, team, pages) {
      $document.scrollTopAnimated(0, 500);
      $scope.team = team.data.results;
      return $scope.pages = pages.data.results;
    }
  ]);

  app.controller('footerAffiliateCtrl', [
    '$scope', 'affiliates', function($scope, affiliates) {
      return $scope.affiliates = affiliates.data.results;
    }
  ]);

}).call(this);
