// Generated by CoffeeScript 1.9.3
(function() {
  'use strict';
  app.controller('headerCtrl', [
    '$window', '$scope', function($window, $scope) {
      if ($window.sessionStorage.username) {
        return $scope.authed = true;
      } else {
        return $scope.authed = false;
      }
    }
  ]);

}).call(this);
